### ISSUE TITLE
Modificações na tela de cadastro de cliente

### ISSUE THREAD

**Issue by netodomingos** [nexus-developers/Sirius#11]
Dividimos as responsabilidades na tela de cadastro de cliente, deixando com o `Modal.js` a responsabilidade de pegar os dados dos inputs e adicionar no banco de dados e no localStorage.

> Porém, tive alguns problemas, principalmente na parte de adição dos dados e um pequeno bug no state do componente

- [x] Resolver Bug na Adição dos dados.
- [x] Resolver Bug no State.
- [x] Resolver Bug no Modal.

**Comment by Sprained** [comment]
O bug era causado por causa o localStorage não estava atualizando o State
Foi colocado o comando para o mesmo na classe Modal e resolvido o mesmo

**Comment by Sprained** [comment]
Bug de cadastro de cliente corrigido no banco de dados. Faltando correção do model

**Comment by Sprained** [comment]
O erro do modal e redux se encontrava que o state entrava em loop quando ia pra false. Solução foi resetar o state com outra variável para impedir o loop
